#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


PAGE_HEADING_RE = re.compile(r"^## Page (?P<page>\d+)\b", flags=re.MULTILINE)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Integrate selected page-level semantic Markdown into a converted document package."
    )
    parser.add_argument("package_dir", help="Converted document package directory.")
    parser.add_argument(
        "--page-semantics",
        default="page_semantics_abtest.jsonl",
        help="JSONL file generated by describe_pages.py.",
    )
    parser.add_argument(
        "--model",
        default="qwen3.7-plus",
        help="Preferred page semantic model to integrate.",
    )
    parser.add_argument(
        "--pages",
        default=None,
        help="Pages to integrate, for example 4,6,8 or 4-8. Defaults to all matching rows.",
    )
    parser.add_argument(
        "--source-content",
        default="content.md",
        help="Source Markdown file inside the package.",
    )
    parser.add_argument(
        "--output-content",
        default="content.integrated.sample.md",
        help="Output integrated Markdown file inside the package.",
    )
    parser.add_argument(
        "--audit-output",
        default="integrated_sample_audit.md",
        help="Output integration audit file inside the package.",
    )
    return parser.parse_args()


def parse_pages(spec: str | None) -> set[int] | None:
    if spec is None:
        return None
    pages: set[int] = set()
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            left, right = part.split("-", 1)
            start = int(left.strip())
            end = int(right.strip())
            if start > end:
                raise ValueError(f"invalid page range: {part}")
            pages.update(range(start, end + 1))
        else:
            pages.add(int(part))
    return pages


def load_rows(path: Path, model: str, pages: set[int] | None) -> dict[int, dict[str, object]]:
    rows: dict[int, dict[str, object]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if row.get("model") != model or row.get("status") != "described":
            continue
        page = int(row["page"])
        if pages is not None and page not in pages:
            continue
        rows[page] = row
    return rows


def extract_recommended_markdown(description: str) -> str:
    lines = description.splitlines()
    start = None
    for index, line in enumerate(lines):
        if "推荐 Markdown" in line:
            start = index + 1
            break
    if start is None:
        markdown = description.strip()
        if not markdown:
            raise ValueError("page semantic description is empty")
        return demote_headings(markdown)
    while start < len(lines) and not lines[start].strip():
        start += 1
    end = len(lines)
    for index in range(start, len(lines)):
        stripped = lines[index].strip()
        if stripped.startswith("- 不确定性") or stripped.startswith("## 不确定性") or stripped.startswith("### 不确定性"):
            end = index
            break
    markdown = "\n".join(lines[start:end]).strip()
    if not markdown:
        raise ValueError("recommended Markdown section is empty")
    return demote_headings(markdown)


def demote_headings(markdown: str) -> str:
    output: list[str] = []
    for line in markdown.splitlines():
        match = re.match(r"^(#{1,5})(\s+.+)$", line)
        if match:
            output.append("##" + match.group(1) + match.group(2))
        else:
            output.append(line)
    return "\n".join(output).strip()


def page_blocks(content: str) -> list[tuple[int | None, int, int]]:
    matches = list(PAGE_HEADING_RE.finditer(content))
    blocks: list[tuple[int | None, int, int]] = []
    if not matches:
        return [(None, 0, len(content))]
    if matches[0].start() > 0:
        blocks.append((None, 0, matches[0].start()))
    for index, match in enumerate(matches):
        page = int(match.group("page"))
        start = match.start()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(content)
        blocks.append((page, start, end))
    return blocks


def page_risk_flags(page: int, original_block: str, semantic_text: str) -> list[str]:
    flags: list[str] = []
    numeric_count = len(re.findall(r"[$¥%]|\d+(?:\.\d+)?", original_block))
    table_count = original_block.count("<table") + original_block.count("|")
    visual_count = original_block.count("**Visual element")
    if numeric_count >= 25:
        flags.append(f"many_numeric_values:{numeric_count}")
    if table_count >= 2:
        flags.append("dense_tables")
    if visual_count >= 3:
        flags.append(f"many_visual_elements:{visual_count}")
    if any(token in semantic_text for token in ["不确定", "冲突", "推断", "单位"]):
        flags.append("semantic_uncertainty_or_unit_issue")
    if page in {4, 6, 8}:
        flags.append("sample_review_page")
    return flags


def integration_summary(model: str, semantics_file: str, pages: list[int]) -> str:
    page_list = ", ".join(str(page) for page in pages) if pages else "none"
    return "\n".join(
        [
            "## Integration Summary",
            "",
            f"- Created at: {datetime.now(timezone.utc).isoformat()}",
            f"- Primary page model: `{model}`",
            f"- Page semantic source: `{semantics_file}`",
            f"- Integrated pages: {page_list}",
            "- Non-integrated pages remain from `content.md`.",
            "",
        ]
    )


def remove_stale_visual_warning_summary(content: str, audit_output: str) -> str:
    lines = content.splitlines()
    output: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if line.startswith("- Warnings:") and "recorded" in line and "audit.md" in line:
            index += 1
            while index < len(lines) and (not lines[index].strip() or lines[index].startswith("  - ")):
                if not lines[index].strip():
                    break
                index += 1
            output.append(
                f"- Original visual verification warnings were superseded by page-level semantic integration; see `{audit_output}` and `page_semantics*.md`."
            )
            continue
        output.append(line)
        index += 1
    return "\n".join(output).rstrip() + "\n"


def insert_summary(content: str, summary: str) -> str:
    lines = content.splitlines()
    if lines and lines[0].startswith("# "):
        return "\n".join([lines[0], "", summary, *lines[1:]]).rstrip() + "\n"
    return summary + "\n" + content


def write_audit(
    path: Path,
    model: str,
    semantics_file: str,
    output_file: str,
    records: list[dict[str, object]],
) -> None:
    integrated = [record for record in records if record["status"] == "integrated"]
    lines = [
        "# Integrated Markdown Audit",
        "",
        f"- Created at: {datetime.now(timezone.utc).isoformat()}",
        f"- Primary page model: {model}",
        f"- Page semantic source: {semantics_file}",
        f"- Output: {output_file}",
        f"- Integrated pages: {len(integrated)}",
        "",
        "## Pages",
        "",
    ]
    for record in records:
        flags = record.get("risk_flags") or []
        flag_text = ", ".join(str(flag) for flag in flags) if flags else "none"
        lines.append(f"- Page {record['page']}: {record['status']}; risk_flags={flag_text}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    package_dir = Path(args.package_dir).resolve()
    content_path = package_dir / args.source_content
    semantics_path = package_dir / args.page_semantics
    if not content_path.exists():
        raise SystemExit(f"source content not found: {content_path}")
    if not semantics_path.exists():
        raise SystemExit(f"page semantics file not found: {semantics_path}")

    requested_pages = parse_pages(args.pages)
    semantic_rows = load_rows(semantics_path, args.model, requested_pages)
    if not semantic_rows:
        raise SystemExit(f"no described rows found for model {args.model}")

    content = content_path.read_text(encoding="utf-8", errors="replace")
    pieces: list[str] = []
    records: list[dict[str, object]] = []
    integrated_pages: list[int] = []

    for page, start, end in page_blocks(content):
        block = content[start:end]
        if page is None or page not in semantic_rows:
            pieces.append(block)
            continue
        row = semantic_rows[page]
        try:
            recommended = extract_recommended_markdown(str(row.get("description") or ""))
        except Exception as exc:
            pieces.append(block)
            records.append({"page": page, "status": "kept_original", "error": str(exc), "risk_flags": []})
            continue
        replacement = (
            f"## Page {page}\n\n"
            f"<!-- integrated_page_semantics model={args.model} source={args.page_semantics} page={page} -->\n\n"
            f"{recommended}\n\n"
        )
        pieces.append(replacement)
        integrated_pages.append(page)
        records.append(
            {
                "page": page,
                "status": "integrated",
                "model": args.model,
                "risk_flags": page_risk_flags(page, block, str(row.get("description") or "")),
            }
        )

    output_content = "".join(pieces)
    output_content = remove_stale_visual_warning_summary(output_content, args.audit_output)
    output_content = insert_summary(
        output_content,
        integration_summary(args.model, args.page_semantics, integrated_pages),
    )

    output_path = package_dir / args.output_content
    audit_path = package_dir / args.audit_output
    output_path.write_text(output_content, encoding="utf-8")
    write_audit(audit_path, args.model, args.page_semantics, args.output_content, records)

    print(f"Wrote integrated content: {output_path}")
    print(f"Wrote integration audit: {audit_path}")
    print(f"Integrated pages: {', '.join(str(page) for page in integrated_pages)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
